apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: rook-ceph-crashcollector
  namespace: rook-ceph
spec:
  endpointSelector:
    matchLabels:
      app: rook-ceph-crashcollector
  ingressDeny:
    - fromEntities:
        - cluster
        - world
        - host
        - remote-node
  egress:
    - toEndpoints:
        - matchLabels:
            app: rook-ceph-mon
      toPorts:
        - ports:
            - port: "3300"
              protocol: TCP
            - port: "6789"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app: rook-ceph-mgr
      toPorts:
        - ports:
            - port: "6800"
              protocol: TCP
