apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: csi-cephfs-ctrlplugin
  namespace: rook-ceph
spec:
  endpointSelector:
    matchLabels:
      app: rook-ceph.cephfs.csi.ceph.com-ctrlplugin
  ingressDeny:
    - fromEntities:
        - cluster
        - world
  egress:
    - toEntities:
        - kube-apiserver
    - toEndpoints:
        - matchLabels:
            app: rook-ceph-mon
      toPorts:
        - ports:
            - port: "3300"
              protocol: TCP
            - port: "6789"
              protocol: TCP
