# Connect Server は不要（Service Account Token 方式）
connect:
  create: false

operator:
  create: true
  authMethod: service-account
  pollingInterval: 1800
  serviceAccountToken:
    name: onepassword-token
  watchNamespace: []
