config:
  existingSecret: oauth2-proxy-ceph-oauth
  cookieName: "_oauth2_proxy_ceph"
  configFile: ""

extraArgs:
  provider: oidc
  oidc-issuer-url: "https://idm.infra.tgy.io/oauth2/openid/oauth2-proxy-ceph"
  redirect-url: "https://ceph.infra.tgy.io/oauth2/callback"
  upstream: "http://rook-ceph-mgr-dashboard.rook-ceph.svc.cluster.local:7000"
  email-domain: "*"
  skip-provider-button: "true"
  code-challenge-method: S256
  reverse-proxy: "true"

service:
  portNumber: 4180

serviceAccount:
  automountServiceAccountToken: false

podDisruptionBudget:
  enabled: false

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 128Mi
