apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: shared-pg-backup
  namespace: database
spec:
  schedule: "CRON_TZ=Asia/Tokyo 0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: shared-pg
