apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: shared-pg-backup
  namespace: database
spec:
  schedule: "0 18 * * *"
  backupOwnerReference: self
  cluster:
    name: shared-pg
