apiVersion: v1
kind: ConfigMap
metadata:
  name: kanidm-server-config
  namespace: kanidm
data:
  server.toml: |
    domain = "idm.tgy.io"
    origin = "https://idm.tgy.io"
    bindaddress = "[::]:8443"
    tls_chain = "/certs/tls.crt"
    tls_key = "/certs/tls.key"
    db_path = "/data/kanidm.db"
    db_fs_type = "other"
