apiVersion: v1
kind: ConfigMap
metadata:
  name: kanidm-repl-config
  namespace: kanidm
data:
  partner-0.toml: |
    [replication."repl://kanidm-1.kanidm-headless.kanidm.svc.cluster.local:8444"]
    type = "mutual-pull"
    partner_cert = "MIICJTCCAcugAwIBAgIBATAKBggqhkjOPQQDAjBMMRswGQYDVQQKDBJLYW5pZG0gUmVwbGljYXRpb24xLTArBgNVBAMMJDA0MjFlYjhhLThhY2UtNDFhMC05ZDI2LWNjZGZhOTRlY2VjNTAeFw0yNjAyMjcxNTA3MDhaFw0zMDAyMjcxNTA3MDhaMEwxGzAZBgNVBAoMEkthbmlkbSBSZXBsaWNhdGlvbjEtMCsGA1UEAwwkMDQyMWViOGEtOGFjZS00MWEwLTlkMjYtY2NkZmE5NGVjZWM1MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEPjxKuGu5jhHXK6I1cqHBdN2O-3iagUnwJtYPhh1AAjDxYuTkyD3DzZ4LJWUeHAWhvmm7uJOCsr2GSOaKr_TXRaOBnTCBmjAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB_wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHQYDVR0OBBYEFNo5o-5ea0sNMlW_75VgGJCv2AcJMDwGA1UdEQQ1MDOCMWthbmlkbS0xLmthbmlkbS1oZWFkbGVzcy5rYW5pZG0uc3ZjLmNsdXN0ZXIubG9jYWwwCgYIKoZIzj0EAwIDSAAwRQIhAPtEGe8sY_1JfXUb1AZQRopvjm8dYs3dM1UKwN97ZImcAiB43MhhbEKg7vyImGv1mLTCGP90T5U6hL4DXN8_zP-iXQ=="
  partner-1.toml: |
    [replication."repl://kanidm-0.kanidm-headless.kanidm.svc.cluster.local:8444"]
    type = "mutual-pull"
    partner_cert = "MIICJDCCAcugAwIBAgIBATAKBggqhkjOPQQDAjBMMRswGQYDVQQKDBJLYW5pZG0gUmVwbGljYXRpb24xLTArBgNVBAMMJDNhOTc5YWFhLTNjNjAtNGU0MS05ZWE2LTNmODMyNmU0Yzk5MDAeFw0yNjAyMjcxNjEwMTlaFw0zMDAyMjcxNjEwMTlaMEwxGzAZBgNVBAoMEkthbmlkbSBSZXBsaWNhdGlvbjEtMCsGA1UEAwwkM2E5NzlhYWEtM2M2MC00ZTQxLTllYTYtM2Y4MzI2ZTRjOTkwMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEZSwhsNQBcwT6OxQ1OdFb5fut2_ymS_Cx-gcXzMytLo3aSK5kRYYSVrfaxulOk1rmNkxlk62KMsi8W0c7HIEi2aOBnTCBmjAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB_wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHQYDVR0OBBYEFNo5o-5ea0sNMlW_75VgGJCv2AcJMDwGA1UdEQQ1MDOCMWthbmlkbS0wLmthbmlkbS1oZWFkbGVzcy5rYW5pZG0uc3ZjLmNsdXN0ZXIubG9jYWwwCgYIKoZIzj0EAwIDRwAwRAIgQQYB-cZ4ft4sU1dBg8aH3keKialWjrAH4SoI1Pdq7ZcCIFMRd34bExBRbTD8SD-vIx34rwrmk2pToz-SL0MEgFQR"
    automatic_refresh = true
