apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kanidm-gateway
  namespace: kanidm
spec:
  gatewayClassName: cilium
  listeners:
    - name: passthrough
      hostname: idm.infra.tgy.io
      port: 443
      protocol: TLS
      tls:
        mode: Passthrough
      allowedRoutes:
        kinds:
          - group: gateway.networking.k8s.io
            kind: TLSRoute
        namespaces:
          from: Same
