apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: kanidm
  namespace: kanidm
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: kanidm
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app: cloudflared
            io.kubernetes.pod.namespace: argocd
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: grafana
            io.kubernetes.pod.namespace: monitoring
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: argocd-server
            io.kubernetes.pod.namespace: argocd
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: argo-workflows-server
            io.kubernetes.pod.namespace: argo
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: oauth2-proxy-hubble
            io.kubernetes.pod.namespace: oauth2-proxy
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: oauth2-proxy-seaweedfs
            io.kubernetes.pod.namespace: oauth2-proxy
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: nextcloud
            io.kubernetes.pod.namespace: nextcloud
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app: harbor
            component: core
            io.kubernetes.pod.namespace: harbor
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: kanidm
      toPorts:
        - ports:
            - port: "8444"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: kanidm
      toPorts:
        - ports:
            - port: "8444"
              protocol: TCP
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
