apiVersion: v1
kind: Service
metadata:
  name: kanidm-headless
  namespace: kanidm
  labels:
    app.kubernetes.io/name: kanidm
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: kanidm
  ports:
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
    - name: replication
      port: 8444
      targetPort: 8444
      protocol: TCP
