apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: seaweedfs-volume
  namespace: seaweedfs
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
      app.kubernetes.io/component: volume
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/component: filer
        - matchLabels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/component: master
        - matchLabels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/component: volume
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/component: master
      toPorts:
        - ports:
            - port: "9333"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/component: volume
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
