apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: seaweedfs-bucket-hook
  namespace: seaweedfs
spec:
  endpointSelector:
    matchLabels:
      batch.kubernetes.io/job-name: seaweedfs-bucket-hook
  ingressDeny:
    - fromEntities:
        - world
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/component: master
      toPorts:
        - ports:
            - port: "9333"
              protocol: TCP
            - port: "19333"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/component: filer
      toPorts:
        - ports:
            - port: "8888"
              protocol: TCP
            - port: "18888"
              protocol: TCP
