apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: seaweedfs-master
  namespace: seaweedfs
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
      app.kubernetes.io/component: master
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/component: master
        - matchLabels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/component: volume
        - matchLabels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/component: filer
      toPorts:
        - ports:
            - port: "9333"
              protocol: TCP
            - port: "19333"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
            io.kubernetes.pod.namespace: monitoring
      toPorts:
        - ports:
            - port: "9327"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/component: master
      toPorts:
        - ports:
            - port: "9333"
              protocol: TCP
            - port: "19333"
              protocol: TCP
