apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: seaweedfs-volume-override
  namespace: seaweedfs
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - interval: 30s
      port: metrics
      scrapeTimeout: 5s
  selector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
      app.kubernetes.io/component: volume
