apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream.yaml
  - crds/tridentorchestrator_crd.yaml
patches:
  - target:
      kind: Deployment
      name: trident-operator
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits/cpu
