apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: talos-build
  namespace: argo
spec:
  endpointSelector:
    matchLabels:
      talos-build: "true"
  ingressDeny:
    - fromEntities:
        - world
  egress:
    - toEntities:
        - kube-apiserver
    - toFQDNs:
        - matchName: "ghcr.io"
        - matchName: "github.com"
        - matchName: "api.github.com"
        - matchPattern: "*.githubusercontent.com"
        - matchName: "dl-cdn.alpinelinux.org"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/component: filer
            io.kubernetes.pod.namespace: seaweedfs
      toPorts:
        - ports:
            - port: "8333"
              protocol: TCP
