apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: kanidm-repl-exchange
  namespace: argo
spec:
  endpointSelector:
    matchLabels:
      kanidm-repl-exchange: "true"
  ingressDeny:
    - fromEntities:
        - world
  egress:
    - toEntities:
        - kube-apiserver
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/component: filer
            io.kubernetes.pod.namespace: seaweedfs
      toPorts:
        - ports:
            - port: "8333"
              protocol: TCP
