apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: events-controller
  namespace: argo
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: argo-events-controller-manager
  ingress: []
  egress:
    - toEntities:
        - kube-apiserver
    - toEndpoints:
        - matchLabels:
            eventbus-name: default
      toPorts:
        - ports:
            - port: "8222"
              protocol: TCP
