apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: workflow-pods
  namespace: argo
spec:
  endpointSelector:
    matchExpressions:
      - key: workflows.argoproj.io/workflow
        operator: Exists
      - key: backup-workflow
        operator: DoesNotExist
      - key: pxe-sync
        operator: DoesNotExist
  ingressDeny:
    - fromEntities:
        - cluster
        - world
  egress:
    - toEntities:
        - kube-apiserver
    - toCIDR:
        - 0.0.0.0/0
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app: rook-ceph-rgw
            io.kubernetes.pod.namespace: rook-ceph
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    - toCIDR:
        - 192.168.0.200/32
        - 192.168.0.201/32
        - 192.168.0.202/32
        - 192.168.0.230/32
        - 192.168.0.231/32
        - 192.168.0.232/32
      toPorts:
        - ports:
            - port: "50000"
              protocol: TCP
