apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: kanidm-backup
  namespace: argo
spec:
  endpointSelector:
    matchLabels:
      kanidm-backup: "true"
  ingressDeny:
    - fromEntities:
        - world
  egress:
    - toEntities:
        - kube-apiserver
    - toFQDNs:
        - matchPattern: "*.r2.cloudflarestorage.com"
        - matchName: "dl.k8s.io"
        - matchPattern: "*.dl.k8s.io"
        - matchPattern: "*.alpinelinux.org"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/component: filer
            io.kubernetes.pod.namespace: seaweedfs
      toPorts:
        - ports:
            - port: "8333"
              protocol: TCP
