apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: workflows-server
  namespace: argo
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: argo-workflows-server
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "2746"
              protocol: TCP
          rules:
            http:
              - {}
    - fromEndpoints:
        - matchLabels:
            sensor-name: tofu-cloudflare
        - matchLabels:
            sensor-name: upgrade-k8s
        - matchLabels:
            app.kubernetes.io/name: argo-workflows-workflow-controller
      toPorts:
        - ports:
            - port: "2746"
              protocol: TCP
  egress:
    - toEntities:
        - kube-apiserver
    - toEndpoints:
        - matchLabels:
            cnpg.io/cluster: shared-pg
            io.kubernetes.pod.namespace: database
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
    - toCIDR:
        - 0.0.0.0/0
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app: rook-ceph-rgw
            io.kubernetes.pod.namespace: rook-ceph
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
