apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: workflows-controller
  namespace: argo
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: argo-workflows-workflow-controller
  ingress:
    - fromEntities:
        - host
      toPorts:
        - ports:
            - port: "6060"
              protocol: TCP
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            cnpg.io/cluster: shared-pg
            io.kubernetes.pod.namespace: database
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: argo-workflows-server
      toPorts:
        - ports:
            - port: "2746"
              protocol: TCP
