apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: pxe-sync
  namespace: argo
spec:
  endpointSelector:
    matchLabels:
      pxe-sync: "true"
  ingressDeny:
    - fromEntities:
        - cluster
        - world
  egress:
    - toEntities:
        - kube-apiserver
    - toFQDNs:
        - matchName: "github.com"
        - matchPattern: "*.github.com"
        - matchPattern: "*.githubusercontent.com"
        - matchPattern: "*.alpinelinux.org"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app: rook-ceph-rgw
            io.kubernetes.pod.namespace: rook-ceph
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    - toCIDR:
        - 192.168.0.241/32
      toPorts:
        - ports:
            - port: "2049"
              protocol: TCP
