apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: tofu-cloudflare-periodic
  namespace: argo
spec:
  schedule: "0 15 * * 0"
  timezone: Asia/Tokyo
  concurrencyPolicy: Replace
  workflowSpec:
    workflowTemplateRef:
      name: tofu-cloudflare
    arguments:
      parameters:
        - name: command
          value: apply
