apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: trident-controller
  namespace: trident
spec:
  endpointSelector:
    matchLabels:
      app: controller.csi.trident.qnap.io
  ingressDeny:
    - fromEntities:
        - cluster
        - world
        - host
        - remote-node
  egress:
    - toEntities:
        - kube-apiserver
    - toCIDR:
        - 192.168.0.240/32
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
