config:
  existingSecret: oauth2-proxy-hubble-oauth
  cookieName: "_oauth2_proxy_hubble"
  configFile: ""

extraArgs:
  provider: oidc
  oidc-issuer-url: "https://idm.infra.tgy.io/oauth2/openid/oauth2-proxy-hubble"
  redirect-url: "https://hubble.infra.tgy.io/oauth2/callback"
  upstream: "http://hubble-ui.kube-system.svc.cluster.local:80"
  email-domain: "*"
  skip-provider-button: "true"
  code-challenge-method: S256
  reverse-proxy: "true"

service:
  portNumber: 4180

serviceAccount:
  automountServiceAccountToken: false

podDisruptionBudget:
  enabled: false

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 128Mi
