apiVersion: trident.qnap.io/v1
kind: TridentBackendConfig
metadata:
  name: qnap-backend
  namespace: trident
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  version: 1
  storageDriverName: qnap-nas
  backendName: qnap
  credentials:
    name: qnap-backend-secret
  storage:
    - serviceLevel: "ストレージプール1"
      labels:
        performance: default
