apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qnap-iscsi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.qnap.io
parameters:
  selector: "performance=default"
  fsType: "ext4"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
