apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord
  namespace: monitoring
spec:
  route:
    receiver: discord
    groupBy: ['namespace', 'alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            value: InfoInhibitor
            matchType: "="
      - receiver: discord-low
        matchers:
          - name: alertname
            value: Watchdog
            matchType: "="
      - receiver: discord
        continue: true
  inhibitRules:
    - sourceMatch:
        - name: severity
          value: critical
          matchType: "="
      targetMatch:
        - name: severity
          value: warning
          matchType: "="
      equal: ['namespace', 'alertname']
    - sourceMatch:
        - name: alertname
          value: InfoInhibitor
          matchType: "="
      targetMatch:
        - name: severity
          value: info
          matchType: "="
      equal: ['namespace']
  receivers:
    - name: "null"
    - name: discord
      discordConfigs:
        - apiURL:
            name: discord-webhook-alertmanager
            key: url
          sendResolved: true
    - name: discord-low
      discordConfigs:
        - apiURL:
            name: discord-webhook-alertmanager-low
            key: url
          sendResolved: true
