apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prometheus-admission
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: prometheus-operator-webhook
  ingressDeny:
    - fromEntities:
        - cluster
        - world
  egress:
    - toEntities:
        - kube-apiserver
