apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: storage
  namespace: argocd
spec:
  description: Storage components (seaweedfs, cnpg, qnap-csi, nfs-provisioner)
  sourceRepos:
    - https://cloudnative-pg.github.io/charts
    - https://github.com/qnap-dev/QNAP-CSI-PlugIn.git
    - https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    - https://seaweedfs.github.io/seaweedfs/helm
    - https://github.com/Tsuguya/home-cluster.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: cnpg-system
    - server: https://kubernetes.default.svc
      namespace: database
    - server: https://kubernetes.default.svc
      namespace: nfs-provisioner
    - server: https://kubernetes.default.svc
      namespace: seaweedfs
    - server: https://kubernetes.default.svc
      namespace: trident
  clusterResourceWhitelist:
    - group: '*'
      kind: CustomResourceDefinition
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
    - group: '*'
      kind: ValidatingWebhookConfiguration
    - group: '*'
      kind: MutatingWebhookConfiguration
    - group: '*'
      kind: Namespace
    - group: '*'
      kind: StorageClass
    - group: ''
      kind: PersistentVolume
    - group: '*'
      kind: CSIDriver
    - group: '*'
      kind: TridentOrchestrator
