apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: security
  namespace: argocd
spec:
  description: Secret management and security scanning
  sourceRepos:
    - https://1password.github.io/connect-helm-charts
    - https://oauth2-proxy.github.io/manifests
    - https://aquasecurity.github.io/helm-charts
    - https://github.com/Tsuguya/home-cluster.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: CustomResourceDefinition
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
