apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: security
  namespace: argocd
spec:
  description: Secret management (1password, secrets)
  sourceRepos:
    - https://1password.github.io/connect-helm-charts
    - https://github.com/Tsuguya/home-cluster.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: 1password
    - server: https://kubernetes.default.svc
      namespace: argo
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: cert-manager
    - server: https://kubernetes.default.svc
      namespace: database
    - server: https://kubernetes.default.svc
      namespace: external-dns
    - server: https://kubernetes.default.svc
      namespace: monitoring
    - server: https://kubernetes.default.svc
      namespace: trident
  clusterResourceWhitelist:
    - group: '*'
      kind: CustomResourceDefinition
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
