apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Core platform components (ArgoCD, Cilium, metrics-server)
  sourceRepos:
    - https://argoproj.github.io/argo-helm
    - https://helm.cilium.io
    - https://kubernetes-sigs.github.io/metrics-server
    - https://github.com/Tsuguya/home-cluster.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: cilium-secrets
  clusterResourceWhitelist:
    - group: '*'
      kind: CustomResourceDefinition
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
    - group: '*'
      kind: ValidatingWebhookConfiguration
    - group: '*'
      kind: MutatingWebhookConfiguration
    - group: '*'
      kind: APIService
    - group: '*'
      kind: GatewayClass
    - group: '*'
      kind: Namespace
