apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: networking
  namespace: argocd
spec:
  description: Networking components (cert-manager, external-dns, gateway)
  sourceRepos:
    - https://charts.jetstack.io
    - https://kubernetes-sigs.github.io/external-dns
    - https://github.com/Tsuguya/home-cluster.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: CustomResourceDefinition
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
    - group: '*'
      kind: ValidatingWebhookConfiguration
    - group: '*'
      kind: MutatingWebhookConfiguration
    - group: '*'
      kind: Namespace
    - group: '*'
      kind: ClusterIssuer
    - group: '*'
      kind: CiliumClusterwideNetworkPolicy
    - group: '*'
      kind: CiliumL2AnnouncementPolicy
    - group: '*'
      kind: CiliumLoadBalancerIPPool
