apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: networking
  namespace: argocd
spec:
  description: Networking components (cert-manager, external-dns, gateway)
  sourceRepos:
    - '*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
