apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: argocd-server
        - matchLabels:
            app.kubernetes.io/name: argocd-application-controller
      toPorts:
        - ports:
            - port: "8081"
              protocol: TCP
  egress:
    - toFQDNs:
        - matchName: "github.com"
        - matchName: "argoproj.github.io"
        - matchName: "1password.github.io"
        - matchName: "grafana.github.io"
        - matchName: "oauth2-proxy.github.io"
        - matchName: "aquasecurity.github.io"
        - matchName: "cloudnative-pg.github.io"
        - matchName: "kubernetes-sigs.github.io"
        - matchName: "prometheus-community.github.io"
        - matchName: "seaweedfs.github.io"
        - matchName: "stakater.github.io"
        - matchName: "ghcr.io"
        - matchPattern: "*.githubusercontent.com"
        - matchName: "charts.jetstack.io"
        - matchName: "helm.cilium.io"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: argocd-redis
      toPorts:
        - ports:
            - port: "6379"
              protocol: TCP
