apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cloudflared
  namespace: argocd
spec:
  endpointSelector:
    matchLabels:
      app: cloudflared
  ingressDeny:
    - fromEntities:
        - world
  egress:
    - toFQDNs:
        - matchPattern: "*.v2.argotunnel.com"
        - matchName: "cftunnel.com"
        - matchName: "h2.cftunnel.com"
        - matchName: "quic.cftunnel.com"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "7844"
              protocol: TCP
            - port: "7844"
              protocol: UDP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: argocd-server
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            eventsource-name: github-webhook
            io.kubernetes.pod.namespace: argo
      toPorts:
        - ports:
            - port: "12000"
              protocol: TCP
