apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: harbor-registry
  namespace: harbor
spec:
  endpointSelector:
    matchLabels:
      app: harbor
      component: registry
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: harbor
            component: core
        - matchLabels:
            app: harbor
            component: jobservice
      toPorts:
        - ports:
            - port: "5000"
              protocol: TCP
            - port: "8080"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
            io.kubernetes.pod.namespace: monitoring
      toPorts:
        - ports:
            - port: "8001"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/component: filer
            io.kubernetes.pod.namespace: seaweedfs
      toPorts:
        - ports:
            - port: "8333"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app: harbor
            component: redis
      toPorts:
        - ports:
            - port: "6379"
              protocol: TCP
