apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: loki
  namespace: rook-ceph
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=false
spec:
  store: ceph-objectstore
  displayName: Loki Log Storage
