apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
  labels:
    gateway-access: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
