apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: trivy-scan-jobs
  namespace: trivy-system
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/managed-by: trivy-operator
  ingressDeny:
    - fromEntities:
        - world
  egress:
    - toCIDR:
        - 0.0.0.0/0
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
