apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: trivy-scan-jobs
  namespace: trivy-system
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/managed-by: trivy-operator
  ingressDeny:
    - fromEntities:
        - world
  egress:
    - toFQDNs:
        - matchName: "mirror.gcr.io"
        - matchName: "registry-1.docker.io"
        - matchName: "auth.docker.io"
        - matchName: "production.cloudflare.docker.com"
        - matchName: "ghcr.io"
        - matchName: "registry.k8s.io"
        - matchPattern: "*.pkg.dev"
        - matchName: "quay.io"
        - matchPattern: "*.quay.io"
        - matchName: "public.ecr.aws"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
