apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: trivy-vulnerability-alerts
  namespace: trivy-system
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: trivy
      rules:
        - alert: TrivyCriticalVulnerability
          expr: >-
            sum by (image_repository, image_tag) (
              trivy_image_vulnerabilities{
                severity="Critical",
                image_repository!~"kube-apiserver|kube-scheduler|kube-controller-manager|coredns/coredns|qnapsystem/.*"
              }
            ) > 0
          for: 1h
          labels:
            severity: critical
          annotations:
            summary: "Critical vulnerabilities in {{ $labels.image_repository }}:{{ $labels.image_tag }}"
            description: "{{ $value }} critical vulnerabilities (with fixes available) in {{ $labels.image_repository }}:{{ $labels.image_tag }}"
