apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: oauth2-proxy-seaweedfs
  namespace: oauth2-proxy
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: oauth2-proxy-seaweedfs
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "4180"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/component: filer
            io.kubernetes.pod.namespace: seaweedfs
      toPorts:
        - ports:
            - port: "8888"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: kanidm
            io.kubernetes.pod.namespace: kanidm
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
