apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: oauth2-proxy-ceph
  namespace: oauth2-proxy
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: oauth2-proxy-ceph
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "4180"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            app: rook-ceph-mgr
            io.kubernetes.pod.namespace: rook-ceph
      toPorts:
        - ports:
            - port: "7000"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: kanidm
            io.kubernetes.pod.namespace: kanidm
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
