apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: tetragon-operator
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: tetragon-operator
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
            io.kubernetes.pod.namespace: monitoring
      toPorts:
        - ports:
            - port: "2113"
              protocol: TCP
  egress:
    - toEntities:
        - kube-apiserver
