apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: sensitive-file-access
spec:
  kprobes:
    - call: "security_file_open"
      syscall: false
      message: "Sensitive credential file opened"
      args:
        - index: 0
          type: "file"
        - index: 1
          type: "int"
      selectors:
        - matchNamespaces:
            - namespace: Pid
              operator: NotIn
              values:
                - "host_ns"
          matchArgs:
            - index: 0
              operator: "Equal"
              values:
                - "/etc/shadow"
          matchActions:
            - action: Post
              rateLimit: "1m"

    - call: "security_file_open"
      syscall: false
      message: "Sensitive proc file accessed"
      args:
        - index: 0
          type: "file"
        - index: 1
          type: "int"
      selectors:
        - matchNamespaces:
            - namespace: Pid
              operator: NotIn
              values:
                - "host_ns"
          matchArgs:
            - index: 0
              operator: "Prefix"
              values:
                - "/proc/kcore"
                - "/proc/kallsyms"
          matchActions:
            - action: Post
              rateLimit: "1m"
