apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-system-config
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/Tsuguya/home-cluster.git
    targetRevision: main
    path: manifests/kube-system
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  ignoreDifferences:
    - group: cilium.io
      kind: TracingPolicy
      jqPathExpressions:
        - .spec.kprobes[]?.args[]? | select(has("type")) | .maxData, .resolve, .returnCopy
        - .spec.kprobes[]? | select(has("call")) | .return
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
