apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-config
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/Tsuguya/home-cluster.git
    targetRevision: main
    path: manifests/1password
  destination:
    server: https://kubernetes.default.svc
    namespace: 1password
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
