apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trident-config
  namespace: argocd
spec:
  project: storage
  source:
    repoURL: https://github.com/Tsuguya/home-cluster.git
    targetRevision: main
    path: manifests/trident
  destination:
    server: https://kubernetes.default.svc
    namespace: trident
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
