apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: talos-custom-build-github-webhook
  namespace: argo
spec:
  itemPath: "vaults/home-cluster/items/talos-custom-build-github-webhook"
