apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kanidm-argo-workflows-oauth
  namespace: argo
spec:
  itemPath: "vaults/am37jjl6mctaze6xsytbxdhu5y/items/oggzannoxdm57w2yoyxveubzhy"
