apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kanidm-grafana-oauth
  namespace: monitoring
spec:
  itemPath: "vaults/am37jjl6mctaze6xsytbxdhu5y/items/h5bme4w2ekcdawkyslx6uyi6xa"
