apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: discord-webhook-alertmanager-low
  namespace: monitoring
spec:
  itemPath: "vaults/home-cluster/items/mcn2zd5y6q5ezglwywup7o3dou"
