apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: oauth2-proxy-seaweedfs-oauth
  namespace: oauth2-proxy
spec:
  itemPath: "vaults/am37jjl6mctaze6xsytbxdhu5y/items/so2kq4jpyrwfnumdcquymigpca"
