apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: oauth2-proxy-ceph-oauth
  namespace: oauth2-proxy
spec:
  itemPath: "vaults/am37jjl6mctaze6xsytbxdhu5y/items/ya7qvq333o5mfi7fuymlvteze4"
