config:
  existingSecret: oauth2-proxy-seaweedfs-oauth
  cookieName: "_oauth2_proxy_seaweedfs"
  configFile: ""

extraArgs:
  provider: oidc
  oidc-issuer-url: "https://idm.tgy.io/oauth2/openid/oauth2-proxy-seaweedfs"
  redirect-url: "https://seaweedfs.infra.tgy.io/oauth2/callback"
  upstream: "http://seaweedfs-filer.seaweedfs.svc.cluster.local:8888"
  email-domain: "*"
  skip-provider-button: "true"
  code-challenge-method: S256
  reverse-proxy: "true"

service:
  portNumber: 4180

serviceAccount:
  automountServiceAccountToken: false

podDisruptionBudget:
  enabled: false

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 128Mi
