logFormat: json

sources:
  - gateway-httproute
  - gateway-tlsroute

provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: credential

policy: sync
registry: txt
txtOwnerId: home-cluster
txtPrefix: _externaldns.

domainFilters:
  - tgy.io
